env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - main: ./cmd/short-season/short-season.go
    id: "cli"
    binary: short-season
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm

  - main: ./cmd/long-season/long-season.go
    id: "server"
    binary: long-season
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
