version: '3'

services:
  app:
    build: .
    volumes:
      - ./db:/opt/db:z
    ports:
      - "3000:3000"
    environment:
      - LS_HOST=127.0.0.1
      - LS_PORT=3000
      - LS_JWT_SECRET=your_super_secret_key
      - LS_APP=long-season
    entrypoint: ["long-season"]
