# https://taskfile.dev

---
version: '2'

vars:
  NAME: long-season
  NAME_CLI: short-season

tasks:
  default:
    deps: [server, cli]

  server:
    cmds:
      - go build -o {{ .NAME }} cmd/long-season/*.go
    sources:
      - ./**/*.go
      - ./**/*.html
      - ./**/*.js
      - ./**/*.css
    generates:
      - ./{{ .NAME }}

  cli:
    cmds:
      - go build -o {{ .NAME_CLI }} cmd/short-season/*.go

  run:
    deps: [server]
    cmds:
      - ./{{ .NAME }}

  clean:
    cmds:
      - rm -f ./{{ .NAME }} ./{{ .NAME_CLI }}

  lint:
    cmds:
      - golint ./...

  test:
    cmds:
      - go test ./...
