# https://taskfile.dev

---
version: '2'

vars:
  NAME: long-season
  NAME_CLI: long-season-cli

tasks:
  default:
    deps: [server, cli]

  server:
    deps: [gen]
    cmds:
      - go build -o {{ .NAME }} cmd/server/main.go
    sources:
      - ./**/*.go
      - ./**/*.html
    generates:
      - ./{{ .NAME }}

  cli:
    cmds:
      - go build -o {{ .NAME_CLI }} cmd/cli/main.go

  run:
    deps: [server]
    cmds:
      - ./{{ .NAME }}

  gen:
    cmds:
      - embedfiles -out=pkg/static/files.gen.go -pkg=static tmpl static
    sources:
      - ./**/*.html
      - ./**/*.css
      - ./**/*.js
    generates:
      - ./pkg/static/files.gen.go

  clean:
    cmds:
      - rm -f ./{{ .NAME }} ./{{ .NAME_CLI }}
      - rm -f ./pkg/static/files.gen.go

  lint:
    cmds:
      - golint ./...

  test:
    cmds:
      - go test ./...
