#!/bin/bash
# send [TARGET] [HOST] [API-KEY]
#
# simple script for sending mac adresses from given local
# target network to given host instance of long-season

while :
do
    NMAP_SCAN=$(sudo nmap -sn $1)
    MACS=$(echo $NMAP_SCAN | grep -ohE "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})")
    echo $MACS | tr ' ' '\n'  | short-season --api $2 --api-key $3
    sleep 5
done
