name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15", "1.14", "1.13"]

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Format Check
      run: |
        if [ $(gofmt -l -s . | wc -l) -ne 0 ]; then echo "gofmt failed"; exit 1; fi

    - name: Embedding Files
      run: |
        env GO111MODULE=off go get 4d63.com/embedfiles
        embedfiles -out=pkg/static/files.gen.go -pkg=static web

    - name: Build
      run: |
        go build -v ./cmd/server/main.go
        go build -v ./cmd/cli/main.go

    - name: Test
      run: go test -v ./...
